"""add_advanced_fields

Revision ID: 285ee0d1715d
Revises: 0f139c227d7b
Create Date: 2025-12-31 20:35:16.775727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '285ee0d1715d'
down_revision: Union[str, Sequence[str], None] = '0f139c227d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('services', sa.Column('extra_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'extra_data')
    op.drop_column('apartments', 'rating')
    # ### end Alembic commands ###
